### DISCUSSION TITLE
How to override the experiment name in mlflow.yml

### DISCUSSION THREAD

**Discussion by ghost** [Galileo-Galilei/kedro-mlflow#495] [General]
Hello,

I have a use case where I have multiple pipelines in my kedro project, and each pipeline has a dedicated mlflow experiment. May I know how can I override the default experiment name with a new one based on the pipeline? 

For example, say the default experiment name in the mlflow.yml file is **x**, and I'm running a kedro pipeline that needs to log the models in the experiment associated with **y** instead of **x**. How do I achieve this?

**Comment by Galileo-Galilei** [comment]
mlflow.yml is just "normal" configuration so this:

```yaml
 #mlflow.yml
 server:
     tracking:
         run:
             name: "${runtime_params:mlflow_run_name, null}"
```
and then ``kedro run --params mlflow_run_name=foo``

"just" work out of the box.

You need to use a recent version with the ``OmegaConfigLoader`` activated though. It will become the default in the upcoming 0.19
