### ISSUE TITLE
Changing default separator for flattening params don't work if dictionnary has depth >1

### ISSUE THREAD

**Issue by Galileo-Galilei** [Galileo-Galilei/kedro-mlflow#230]
## Description

Changing the default ``hooks.nodes.sep`` `separator in the mlflow.yml does only work when the flattened dictionnary has depth one.

## Context

> How has this bug affected you? What were you trying to accomplish?

I was trying to change the default separator when flattening dict parameters.

## Steps to Reproduce

1. Create a kedro project
2. Create mlflow.yml with ``kedro mlflow init``
3. Change the default config:

```yaml
# conf/local/mlflow.yml

hooks:
  node:
    flatten_dict_params: True  # Changed, default is True
    recursive: True  
    sep: "_" # Changed, default is "."
    long_parameters_strategy: fail 
```

```yaml
# conf/base/parameters.yml

nested_params:
  a: 1
  b: 
    b1: 1
    b2: 2
```

4. Use this parameter in a node
5. Launch kedro run

## Actual Result vs expected

The following parameters are then logged in mlflow:
-``nested_params_a = 1``
-``nested_params_b.b1 = 1`` (expected result is ``nested_params_b_b1 = 1``)
-``nested_params_b.b2 = 2`` (expected result is ``nested_params_b_b2 = 1``)

## Solution: 

The faulty line is 

https://github.com/Galileo-Galilei/kedro-mlflow/blob/b3c1e264f7968527e8cc551fceab0ea86573d6c4/kedro_mlflow/framework/hooks/node_hook.py#L136

Because arguments are not passed to the recursive call to ``flatten_dict``
