### ISSUE TITLE
Track the globals parameters used in the DataCatalog when using the TemplatedConfigLoader

### ISSUE THREAD

**Issue by nblumoe** [Galileo-Galilei/kedro-mlflow#253]
## Description
Allow parameters to be used in the catalog and track them to MLflow.

## Context
Some data sources might be parameterised (e.g. via SQL `SELECT * FROM my_data WHERE date = <DATE-PARAM>`) and this should get tracked to MLflow too.

## Possible Implementation
Instead of just checking for params usage on Nodes, kedro-mlflow would also need to track params being used elsewhere. Could it just track all params, independently from where they are used.

I am not sure if kedro even allows such parameterised data sources in the catalog, thus this might required an upstream change on kedro first.

**Comment by nblumoe** [comment]
Thanks for looking into this!

Does your first bullet point indicate that kedro should be able to handle params in the catalog? I didn't have luck with this yet:

```yml
# parameters.yml
timestamp: 2021-10-13

# catalog.yml
# reduced to essential data, this is not a complete catalog entry
my_data:
  sql: select * from my_table where timestamp = ${params.timestamp}
```

`${params.timestamp}` doesn't get replaced in the catalog when the actual SQL query is executed.
