### ISSUE TITLE
MlflowArtifactDataSet does not work with PartitionedDataSet

### ISSUE THREAD

**Issue by Galileo-Galilei** [Galileo-Galilei/kedro-mlflow#258]
## Description

It is not possible to store a ``PartitionedDataSet`` as an mlflow artifact with the ``MlflowArtifactDataSet``.

## Context

I had a use case where I need to save a dict with many small result tables to mlflow, and I tried to use ``PartitionedDataSet`` for this.

## Steps to Reproduce

```yaml
# catalog.yml

my_dataset:
    type: kedro_mlflow.io.artifacts.MlflowArtifactDataSet
    data_set:
        type: PartitionedDataSet  # or any valid kedro DataSet
        path: /path/to/a/local/folder # the attribute is "path", and not "filepath"!
        dataset: "pandas.CSVDataSet"
```

then save a dict using this dataset:

```
catalog.save("my_dataset", dict("a": pd.DataFrame(data=[1,2,3], columns=["a"], "b": pd.DataFrame(data=[1,2,3], columns=["b"])
```
## Expected Result

The 2 Dataframes should be logged as artifacts in the current mlflow run.

## Actual Result

An error ``dataset has not attribute "_filepath"`` is raised.

## Does the bug also happen with the last version on master?

Yes

## Potential solution

The error comes from this line:

https://github.com/Galileo-Galilei/kedro-mlflow/blob/904207ad505b71391d78d8088aaed151ca6a011d/kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py#L53

maybe we can add a better condition here to default to "path" if there is no "filepath" attribute.
