### ISSUE TITLE
Joblib Format

### ISSUE THREAD

**Issue by nitishbharti** [Galileo-Galilei/kedro-mlflow#319]
Is there any way to save "model.pkl" as "model.joblib" in model versioning. 
**_catalog.yml_** 
```
example_model:
  type: kedro_mlflow.io.artifacts.MlflowArtifactDataSet
  data_set:
    type: kedro_mlflow.io.models.MlflowModelSaverDataSet
    flavor: mlflow.sklearn
    filepath: data/06_models/sklearn_model
```

**Comment by Galileo-Galilei** [comment]
Hi, 

basically ``kedro-mlflow`` can do anything ``mlflow`` can, but I do not add extra features to logging. 

Looking at [``mlflow.sklearn`` flavor documentation]
(https://www.mlflow.org/docs/latest/python_api/mlflow.sklearn.html#mlflow.sklearn.log_model), we can see that there is a ``serialization_format`` argument :

> **serialization_format** – The format in which to serialize the model. This should be one of the formats listed in mlflow.sklearn.SUPPORTED_SERIALIZATION_FORMATS. The Cloudpickle format, mlflow.sklearn.SERIALIZATION_FORMAT_CLOUDPICKLE, provides better cross-system compatibility by identifying and packaging code dependencies with the serialized model.

Let's look at available formats:

```python
from mlflow.sklearn import SUPPORTED_SERIALIZATION_FORMATS
print(SUPPORTED_SERIALIZATION_FORMATS) # ['pickle', 'cloudpickle']
```

``joblib`` is unfortunately not supported currently. If you want **to make it available, you should open an issue directly in mlflow repo.** 


### Example with kedro-mlflow

If you want to change the serialisation format, add these lines in your catalog:

```
example_model:
  type: kedro_mlflow.io.artifacts.MlflowArtifactDataSet
  data_set:
    type: kedro_mlflow.io.models.MlflowModelSaverDataSet
    flavor: mlflow.sklearn
    filepath: data/06_models/sklearn_model
    save_args:
        serialization_format: pickle  # put joblib here when it will be available in mlflow
```

**Comment by nitishbharti** [comment]
Thank you @Galileo-Galilei

**Comment by tpanthera** [comment]
Hey @Galileo-Galilei thanks for quick responses.
Interestingly below code serves our purpose of saving model as joblib, let me know if you see any loop hole.

```
example_model:
  type: kedro_mlflow.io.artifacts.MlflowArtifactDataSet
  data_set:
    type: pickle.PickleDataSet
    backend: joblib
    filepath: data/06_models/sklearn_model/model.joblib
```
