### ISSUE TITLE
Issue with kedro_mlflow and seldon integration

### ISSUE THREAD

**Issue by nitishbharti** [Galileo-Galilei/kedro-mlflow#326]
Seldon requires mlflow with "python_function" flavour. As shown below and also mentioned [here](https://youtu.be/fmwyQjfL26k?t=882) 
<img width="346" alt="Capture" src="https://user-images.githubusercontent.com/43014230/171397137-727523b6-4260-4459-9fc8-6fc844986428.PNG">

But artifacts of mlflow doesn't have "python_function" flavour. as shown below.
<img width="325" alt="Capture1" src="https://user-images.githubusercontent.com/43014230/171397621-289ff595-0c1b-4641-b057-001aa5a5c367.PNG">

Can you please suggest what changes should I make in "catalog.yml" or somewhere in order to acheive this, so that I can deploy it on seldon.

**Comment by nitishbharti** [comment]
Thanx @Galileo-Galilei.

**Comment by Galileo-Galilei** [comment]
You're welcome. Obviously it is recommended to use the ``MlflowModel<Logger/Saver>Dataset`` in the ``catalog.yml`` instead of the python API in above example, e.g. :

```yaml
# catalog.yml
type: kedro_mlflow.io.MlflowArtifactDataSet
data_set: 
    type: kedro_mlflow.io.models.MlflowModelSaverDataSet
    filepath:  path/to/model.pkl
    flavor: mlflow.sklearn
```

If it's good for you, I close the issue. Feel free to reopen.
