### ISSUE TITLE
Modify logging level to info to match kedro's one

### ISSUE THREAD

**Issue by Galileo-Galilei** [Galileo-Galilei/kedro-mlflow#348]
## Description

The default logging level in kedro has changed (see https://github.com/kedro-org/kedro/issues/1732) to "warning" in kedro==0.18.2 to match python's default, and ``kedro-mflow`` logs are not displayed anymore

## Context

Logging messages are useful to understand what kedro-mlflow does under the hood. 

## Possible Implementation

Use ``after_context_created`` hook to modify logging configuration. 

## Possible Alternatives

- Alternative 1: Ask users to add
```yaml
loggers:
    kedro:
        level: INFO
    <my_package>:
        level: INFO
    kedro-mlflow:
        level: INFO
```
 in their ``logging.yml`` file. This does not seem very user friendly.

- Alternative 2: Set all logger to "warning" to make them visible again. This does look unnecessary scary for users.
