### ISSUE TITLE
Download mlflow artifact

### ISSUE THREAD

**Issue by Groskilled** [Galileo-Galilei/kedro-mlflow#415]
Hi !

I am trying to download csv files from a mlflow run.
I tried everything I could think of, and most of the times I get `Run run_id not found` error.
Here's what I am using

```
dataframe:
  type: kedro_mlflow.io.artifacts.MlflowArtifactDataSet
  data_set:
    type: pandas.CSVDataSet
    filepath: contribution_df.csv
  run_id: run_id
```

I don't know what I am missing. The run_id I am using works juste fine when I use MlflowClient().download_artifacts()

Have a nice day :)
