### ISSUE TITLE
Kedro-mlflow with kedro 0.19.11 produces multiple runs

### ISSUE THREAD

**Issue by gozderam** [Galileo-Galilei/kedro-mlflow#624]
## Description
Once upgraded kedro to 0.19.11, kedro-mlflow started to produce multiple runs  in MLFlow. 

## Context

There are additional runs in MLFlow once running `kedro run` while only one is expected. When downgrading kedro back to 0.19.10 this problem does not occur. 

## Steps to Reproduce

1. Create a new kedro project, can be exemplary [spaceflights project](https://docs.kedro.org/en/stable/tutorial/tutorial_template.html) with kedro==0.19.11. 
2. Add kedro-mlflow package and `mlflow.yml` file.
3. In catalog, make one of the datasets a MLFlow artifact, e.g. for spaceflights:
```
preprocessed_companies:
  type: kedro_mlflow.io.artifacts.MlflowArtifactDataset
  dataset:
    type: pandas.ParquetDataset
    filepath: data/02_intermediate/preprocessed_companies.parquet
```
4. run `kedro run`

## Expected Result

One run is produced in MLFlow.

## Actual Result

MLFlow produces two runs, one with "__default__" name and the other one with some random name. 

## Your Environment

* `kedro` and `kedro-mlflow` version used (`pip show kedro` and `pip show kedro-mlflow`):
kedro: 0.19.11  (this problem does not occur in 0.19.10!)
kedro-mlflow: 0.14.0
* Python version used (`python -V`):
3.11
* Operating system and version:
Mac os Sonoma 14.4
## Does the bug also happen with the last version on master?
yes
