### ISSUE TITLE
`MlflowArtifactDataset` wrapping `PartitionedDataset` saves all files from given `path`, not only those generated during a run

### ISSUE THREAD

**Issue by yury-fedotov** [Galileo-Galilei/kedro-mlflow#651]
## Description
`MlflowArtifactDataset` wrapping `PartitionedDataset` saves **all files from given `path`**, not only those generated during a run, during each run.

## Context

This makes `MlflowArtifactDataset` wrapping `PartitionedDataset` not super convenient in experiment names where partition names change. 

## Steps to Reproduce

Consider this example:

```yaml
"profiling.{dataset}.partitioned_focused_pairplots":
  type: kedro_mlflow.io.artifacts.MlflowArtifactDataset
  artifact_path: profiling/{dataset}
  dataset:
    type: partitions.PartitionedDataset
    path: data/08_reporting/{dataset}/partitioned_focused_pairplots/
    dataset: matplotlib.MatplotlibDataset
```

Where we save a bunch of images to `profiling/{dataset}` directory of MLflow.

1. Let's say that during the first run, images called `a.png` and `b.png` were generated and logged.
2. During the second run, different images but under the same names were generated and logged. So far all good.
3. During the third run, images called `c.png` and `d.png` were generated. But what is logged against this run is them **plus** the `a.png` and `b.png` from second run, as they're still present in `data/08_reporting/{dataset}/partitioned_focused_pairplots/`.

## Expected Result

Only files generated during a particular run should be logged against it, not entire local folder defined by `path` argument.

## Actual Result

Entire contents of the local `path` folder gets logged for each run, including artifacts not generated during it.

## Your Environment

* `kedro` and `kedro-mlflow` version used (`pip show kedro` and `pip show kedro-mlflow`): Kedro 0.19.10 and Kedro-mlflow 0.14.4
* Python version used (`python -V`): 3.10
* Operating system and version: Windows

**Comment by yury-fedotov** [comment]
Oh nice, thank you!

I played with it, the correct syntax is a bit different and simpler:

```yaml
profiling.partitioned_focused_pairplots:
  type: kedro_mlflow.io.artifacts.MlflowArtifactDataset
  artifact_path: profiling
  dataset:
    type: matplotlib.MatplotlibDataset
    filepath: data/08_reporting/partitioned_focused_pairplots/
    overwrite: true
```

So `matplotlib.MatplotlibDataset` actually does the job of `partitions.PartitionedDataset` itself because it's capable of saving a `dict[str, Figure]`.
