### ISSUE TITLE
MlflowDataSet fails to log on remote storage when underlying dataset filepath is converted as a PurePosixPath

### ISSUE THREAD

**Issue by Galileo-Galilei** [Galileo-Galilei/kedro-mlflow#74]
When I register a dataset in the catalog.yml

```yaml
my_dataset:
  type : kedro_mlflow.io.MlflowDataSet 
  data_set : 
    type: pickle.PickleDataSet
    filepath: data/02_intermediate/my_dataset.pkl
```

and I run `kedro run` I got a `expected string or bytes-like object` when **the local path is linux AND the `mlflow_tracking_uri` is an Azure blob storage (it works locally)**. I don't know really why this append, but it can be fied by replacing `self._filepath` by `self._filepath.as_posix()` in these 2 locations: 

https://github.com/Galileo-Galilei/kedro-mlflow/blob/94bae3df9a054c85dfc0bf13de8db876363de475/kedro_mlflow/io/mlflow_dataset.py#L51

https://github.com/Galileo-Galilei/kedro-mlflow/blob/94bae3df9a054c85dfc0bf13de8db876363de475/kedro_mlflow/io/mlflow_dataset.py#L55

@kaemo @akruszewski did you experience some issues with S3 too?

**EDIT**: @akruszewski it is [the very same issue you encountered here](https://github.com/akruszewski/kedro-mlflow/commit/41e9e3fdd2c54a774cca69e1cb52e26cadf50b1e)
